server:
  port: 8882
logging: 
  file: c:/app.log
  level:
    ROOT: INFO
spring:
  cloud:
    consul:
      host: 159.75.38.24
      port: 8500
      discovery: # 服务发现配置
        enabled: true
        register: true
        deregister: true
        prefer-ip-address: true
        health-check-interval: 10s
        health-check-critical-timeout: 30s
        health-check-path: /hello
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  security:
    user:
      name: hdy
      password: 1995415
  redis:
    database: 2
    host: 159.75.38.24
    port: 6379
    password: Zxc1995415
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
management:
  endpoints:
    web:
      exposure:
        include: 
        - "*"  # 开放所有端点health，info，metrics，通过actuator/+端点名就可以获取相应的信息。默认打开health和info
  endpoint:
    health:
      show-details: always  #未开启actuator/health时，我们获取到的信息是{"status":"UP"}，status的值还有可能是 DOWN。开启后打印详细信息